/* 
 * predictor_scoring
 *
 * Credit Score Predictor
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StartBatchExecutionResponse
    /// </summary>
    [DataContract]
    public partial class StartBatchExecutionResponse :  IEquatable<StartBatchExecutionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StartBatchExecutionResponse" /> class.
        /// </summary>
        /// <param name="batchExecutionId">Id of the asynchronous execution..</param>
        public StartBatchExecutionResponse(string batchExecutionId = default(string))
        {
            this.BatchExecutionId = batchExecutionId;
        }
        
        /// <summary>
        /// Id of the asynchronous execution.
        /// </summary>
        /// <value>Id of the asynchronous execution.</value>
        [DataMember(Name="batchExecutionId", EmitDefaultValue=false)]
        public string BatchExecutionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StartBatchExecutionResponse {\n");
            sb.Append("  BatchExecutionId: ").Append(BatchExecutionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StartBatchExecutionResponse);
        }

        /// <summary>
        /// Returns true if StartBatchExecutionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StartBatchExecutionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StartBatchExecutionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BatchExecutionId == input.BatchExecutionId ||
                    (this.BatchExecutionId != null &&
                    this.BatchExecutionId.Equals(input.BatchExecutionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BatchExecutionId != null)
                    hashCode = hashCode * 59 + this.BatchExecutionId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
