/* 
 * predictor_scoring
 *
 * Credit Score Predictor
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OutputParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutputParametersTests
    {
        // TODO uncomment below to declare an instance variable for OutputParameters
        //private OutputParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OutputParameters
            //instance = new OutputParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OutputParameters
        /// </summary>
        [Test]
        public void OutputParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputParameters
            //Assert.IsInstanceOfType<OutputParameters> (instance, "variable 'instance' is a OutputParameters");
        }


        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Test]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

    }

}
