/* 
 * predictor_scoring
 *
 * Credit Score Predictor
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebServiceResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebServiceResultTests
    {
        // TODO uncomment below to declare an instance variable for WebServiceResult
        //private WebServiceResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebServiceResult
            //instance = new WebServiceResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebServiceResult
        /// </summary>
        [Test]
        public void WebServiceResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebServiceResult
            //Assert.IsInstanceOfType<WebServiceResult> (instance, "variable 'instance' is a WebServiceResult");
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'ConsoleOutput'
        /// </summary>
        [Test]
        public void ConsoleOutputTest()
        {
            // TODO unit test for the property 'ConsoleOutput'
        }
        /// <summary>
        /// Test the property 'ChangedFiles'
        /// </summary>
        [Test]
        public void ChangedFilesTest()
        {
            // TODO unit test for the property 'ChangedFiles'
        }
        /// <summary>
        /// Test the property 'OutputParameters'
        /// </summary>
        [Test]
        public void OutputParametersTest()
        {
            // TODO unit test for the property 'OutputParameters'
        }

    }

}
